### ISSUE TITLE
"JST" battery header confusion

### ISSUE THREAD

**Issue by dcoles** [TinyWATCH-S3/Official-hardware#2]
My TinyWATCH arrived today (thank you for the quick shipping!), but I'm a little confused which battery connector is on the PCB.

The [IBOM](https://github.com/TinyWATCH-S3/Official-hardware/blob/main/TinyWATCH%20S3%20revision%20P4/ibom/ibom.html) lists it as a "2P-MICROBLADE" with a "JST-PICOBLADE" footprint, while the [KiCAD schematic](https://github.com/TinyWATCH-S3/Official-hardware/blob/main/TinyWATCH%20S3%20revision%20P4/KiCAD%207.0.10/TinyWATCH_S3_P4.kicad_pcb) says it's a "2-Pin JST PH Series Right-Angle Connector", though it's too small for any of my existing my existing LiPo batteries with 2mm JST PH connectors.

I'm pretty sure it's a [Molex PicoBlade](https://www.mouser.com/new/molex/molex-picoblade/) given the 1.25mm pitch.

I somehow lucked out already having a box of [Molex PicoBlade "compatible" connectors](https://www.amazon.com/1-25mm-Connectors-Pre-Crimped-Pixhawk-Silicone/dp/B07S18D3RN/). It's a bit of a tight fit behind the magnetic buzzer, but mates quite snugly.

**Comment by UnexpectedMaker** [comment]
Fixed, thanks!
